version: "3"
services:
  type:
    container_name: inventory-management
    image: inventory-management:latest
    restart: on-failure
    env_file: .env
    build: .
    depends_on:
      - database
    environment:
      DATABASE_URL: ${DATABASE_URL}
      NODE_ENV: production
      PORT: 4000
    ports:
      - "4000:4000"
    command: npm run start
    volumes:
      - app-data:/inventory-management

  database:
    image: postgres:latest
    container_name: inventory-management-database
    restart: on-failure
    ports:
      - "35432:5432"
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: inventory
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  app-data:
  db-data: 